Bugfix/condicoes clinicas de base
EscolaDeSaudePublica/registrocovid-front pull request #103
Opened 2020-09-24 19:39 UTC by ericsonmoreira

## **Ajustes**

- [x] Ajustar texto do menu superior e do título. O nome da página é: **Comorbidades / Condições clínicas de base** e deve aparecer assim em todos os lugares que referenciam a página.

- [x] Renomear o texto: **"Usou corticosteroides por mais de 15 dias?"**
Por: **"Faz uso crônico de corticóides?"**

- [x] Tirar **quimioterapia** do chips ( Selecione as doenças que o paciente apresenta), e colocar ela acima de Transplantado, com radio buttons (sim/ não)

- [x] Tirar **neoplasia** do chips de doenças (esconder da listagem)

- [x] Na doença **hipertensão**, excluir (pressão arterial) - deixar apenas hipertensão

Se basear no protótipo https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=355%3A491

2020-09-25 12:21 UTC, FelipeSVidal approved these changes

2020-09-28 15:12 UTC, chicaothiago requested changes
Remover uns log do código. E alguns comentários extras.

2020-09-28 15:12 UTC, oxechicao commented on src/layouts/Main/components/Sidebar/Sidebar.js
>          {/* <Divider className={classes.divider} /> */}
Necessita realmente manter este código comentado?

2020-09-28 15:12 UTC, oxechicao commented on src/views/Comorbidities/Comorbidities.js
> +
Se já foi testado remover console log.

2020-09-28 15:12 UTC, oxechicao commented on src/views/Comorbidities/Comorbidities.js
> +                    key={index}
O linter não reclama se usar o index como key? Em outro projeto ele solicitava que não usasse index. Aí criei uma função auxiliar que retornava um index aleatório :D

2020-09-28 15:12 UTC, chicaothiago commented on src/views/PersonalHistory/PersonalHistory.js
> +          : '',
Não seira mais interessante uma função para retornar este objeto? Algo que fizesse o map do form. Externo ao componente, se não há um arquivo que referencie um modelo, talvez fosse uma boa criar.
Só uma ideia ;)

2020-09-28 17:13 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +                    key={index}
Comigo não reclama. Com mais alguém isso acontece? Inclusive, teve até uma vez que estavam passando **Math.random()** para um **key** e eu pedi pra remover.

2020-09-28 17:15 UTC, ericsonmoreira commented on src/views/PersonalHistory/PersonalHistory.js
> +          : '',
Sim... faz sentido. Até por que esse é um objeto que tem muitos atributos. Vou dar uma olhada nisso.

2020-09-28 17:17 UTC, ericsonmoreira commented on src/layouts/Main/components/Sidebar/Sidebar.js
>          {/* <Divider className={classes.divider} /> */}
Realmente não. Vou ver isso.

2020-09-28 17:20 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +
Nesse momento encontrei um **bug**. O que acontece é que esse código não está no mesmo padrão dos outros formulários. Daí, ainda estou tentando resolver esse bug que apareceu. Pensando seriamente em refazer essa código para que fiquei no mesmo padrão dos outros _forms_. Opiniões?

2020-09-29 12:52 UTC, chicaothiago commented on src/views/Comorbidities/Comorbidities.js
> +                    key={index}
Talvez fosse porque eu usava o lint do airbnb. Não vi qual estão utilizando.

2020-09-29 12:56 UTC, chicaothiago commented on src/views/Comorbidities/Comorbidities.js
> +
Passa o form para utilizar o padrão novo proposto utilizando formik+material apresentado. 
Se este for o padrão mencionado, arrocha.
Se não foi, aconselho a começar a implementar tudo utilizando Formik, para ao menos ter os primeiros exemplos para futuras features.
Lembrar sempre de mencionar nos próximos cards para utilizar o formik.

2020-09-29 12:57 UTC, chicaothiago commented on src/layouts/Main/components/Sidebar/Sidebar.js
>          {/* <Divider className={classes.divider} /> */}
Acredito que se passou no deskcheck, é porque não usa mais :D

2020-09-29 18:05 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +
@chicaothiago, foi aberto um card para converter esse form para o _Formik_. Agora em diante, vou atentar ao fato de mencionar que os _forms_ precisam ser feitos usando o Formik. Valeu! :+1:

2020-09-29 18:07 UTC, ericsonmoreira commented on src/views/PersonalHistory/PersonalHistory.js
> +          : '',
@chicaothiago, como um Card foi aberto para refatorar essa página, então vamos deixar para colocar isso na refatoração.

2020-09-29 18:52 UTC, MatheusVarela19 approved these changes

2020-09-30 16:42 UTC, chicaothiago approved these changes
Apesar do mesmo lance do outro [PR](https://github.com/EscolaDeSaudePublica/registrocovid-front/pull/108/files#r497648479) quanto ao comentário de quimioterapia definindo um contexto na view. Foi o único ponto aqui.

Ta suave de joiado.

2020-09-30 17:09 UTC, merged