Feature/logo redo
EscolaDeSaudePublica/registrocovid-front pull request #109
Opened 2020-09-29 19:19 UTC by MatheusVarela19

Changed logos and page's name.

2020-09-29 19:25 UTC, ericsonmoreira commented on src/layouts/Main/components/Sidebar/Sidebar.js
>          {/* <Profile /> */}
Esses comentários eu já removi em uma outra _branch_.

2020-09-29 19:27 UTC, ericsonmoreira approved these changes
GTM :+1:

2020-09-29 21:25 UTC, FelipeSVidal requested changes
Esse PR vai gerar conflito com a issue #97 
Por causa das alterações no Comorbidities/Comorbidities.js

2020-09-29 21:25 UTC, FelipeSVidal commented on src/views/Comorbidities/Comorbidities.js
> +
Remover console.log

2020-09-30 16:48 UTC, chicaothiago requested changes
A atividade é somente para alterar logo e titulo e existem alguns arquivos que não fazem sentido com a atividade.

Suspeito que houve alguma alteração de **branch** que misturou código de duas features.

Sugiro corrigir este problema e enviar somente o que realmente foi alterado para solucionar a issue em questão.

2020-10-02 02:57 UTC, FelipeSVidal approved these changes

2020-10-06 14:07 UTC, chicaothiago approved these changes

2020-10-06 17:38 UTC, merged