fix header, text fields
EscolaDeSaudePublica/registrocovid-front pull request #110
Opened 2020-09-29 21:09 UTC by FelipeSVidal

- Os nomes dos campos que foram alterados:
  - "UTI" por "Admissão na Unidade de Terapia Intensiva (UTI); 
  - "SARA" por "Síndrome da Angústia Respiratória Aguda (SARA);
  - "Fenômenos tromboembólicos (TVP)" por "Trombose venosa profunda (TVP)", 
  - "Fenômenos tromboembólicos (TEP)" por "Tromboembolismo pulmonar (TEP)";  
  - Acrescentar as opções "Outros fenômenos tromboembólicos" e "Outras" - devem seguir o mesmo padrão de Complicações  neurológicas

- Os campos novos: "Outros fenômenos tromboembólicos" e "Outras"
terão campos de data e campo aberto

Olhar [figma](https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=1048%3A56)

2020-09-30 17:01 UTC, chicaothiago requested changes
O maior problema encontrado foram funcionalidades que somente existe a partir do node v14, e projeto de longa duração deve-se optar por versões LTS do Node.
Aberto a discussões.

2020-09-30 17:01 UTC, oxechicao commented on src/views/Complications/Complications.js
> +          ? complicacao.glasgow_admissao_uti
Qual a diferença entre manter undefined e enviar o null?

2020-09-30 17:01 UTC, oxechicao commented on src/views/Complications/components/NeurologicForm/NeurologicForm.js
> +  console.log('19', complicationData);
remover log

2020-09-30 17:01 UTC, oxechicao commented on src/views/Complications/components/NeurologicForm/NeurologicForm.js
> +                ? !!errors.newsComplicacoes[index]?.data
É garantido que a nova sintax vai funcionar no servidor? ou quem vá fazer o build estará com a versão mais nova? Acredito que o desenvolvimento deva ser usando a ultima LTS do node para evitar conflitos, mesmo tendo coisa boa na ultima versão.

2020-09-30 17:01 UTC, oxechicao commented on src/views/Complications/components/NeurologicForm/NeurologicForm.js
> +                ? errors.newsComplicacoes[index]?.data
A mesma questão do comentário acima sobre versão de node, Optional chaining (?.) é a partir do node v14

2020-09-30 17:01 UTC, oxechicao commented on src/views/Complications/components/NeurologicForm/NeurologicForm.js
> +                ? !!errors.newsComplicacoes[index]?.descricao
Mesma questão sobre o Optional chaining (?.)

2020-09-30 17:01 UTC, oxechicao commented on src/views/Complications/components/NeurologicForm/NeurologicForm.js
> +                ? errors.newsComplicacoes[index]?.descricao
Mesmo aqui Optional chaining (?.)

2020-09-30 17:01 UTC, oxechicao commented on src/views/Complications/components/NeurologicItem/NeurologicItem.js
> +// eslint-disable-next-line react/display-name
Remover o ignore e tratar o problema do lint de forma correta. Se não o lint fica triste e nos abandona.

2020-10-01 17:12 UTC, FelipeSVidal commented on src/views/Complications/Complications.js
> +          ? complicacao.glasgow_admissao_uti
Se não me engano é porque se enviar undefined dá erro no back.

2020-10-01 17:25 UTC, FelipeSVidal commented on src/views/Complications/components/NeurologicForm/NeurologicForm.js
> +                ? !!errors.newsComplicacoes[index]?.data
Não estava no escopo do PR, mas vou ver como isso funciona e adequo!

2020-10-06 14:13 UTC, chicaothiago approved these changes
Há só um ponto do lint necessitando de uma nova linha ao fim do arquivo. Mas, para isso não ser qualquer aviso nas próximas alterações do projeto ,recomendo a implantação do Husky no projeto, assim probleminhas de linter nunca irão subir para PR.

2020-10-06 14:13 UTC, chicaothiago commented on src/views/Complications/components/DefaultItem/DefaultItem.js
> +export default DefaultItem;
o lint no próprio github diz que falta 1 nova linha ao fim do arquivo.

2020-10-06 17:44 UTC, MatheusVarela19 approved these changes

2020-10-06 17:47 UTC, ericsonmoreira commented on src/views/Complications/components/ComplicationsList/ComplicationsList.js
> +                  } else if (complicacao.tipo_complicacao_id >= 13) {
Aqui não deveria ser `>==` em vez de `>=` ?

2020-10-06 17:47 UTC, ericsonmoreira commented on src/views/Complications/components/ComplicationsList/ComplicationsList.js
> +          } else if (complicacao.tipo_complicacao.id >= 13) {
Aqui não deveria ser `>==` em vez de `>=` ? (igual ao anterior)

2020-10-06 17:50 UTC, ericsonmoreira approved these changes
GTM :+1: 

Dá só uma olhada no comentário que eu fiz.

2020-10-06 18:00 UTC, FelipeSVidal commented on src/views/Complications/components/ComplicationsList/ComplicationsList.js
> +                  } else if (complicacao.tipo_complicacao_id >= 13) {
Sim, vou mudar antes de dar o merge!

2020-10-06 18:02 UTC, merged