Bugfix/suporte respiratorio
EscolaDeSaudePublica/registrocovid-front pull request #114
Opened 2020-10-07 20:07 UTC by ericsonmoreira

## Página da Categoria de Suporte Respiratório

### Contexto

Alguns tipos de suporte novos foram acrescentados ao seeds tipo de suporte, e esses novos seeds devem ser incluídos no frontend da página. Além disso, alguns dos outros campos foram renomeados.

### :atom_symbol:  Missões :rocket: 

- [x] Verificar se os ajustes realizados nos campos existentes foram refletidos no Front da página:
  - [x] Catéter nasal de baixo fluxo - era Cateter de o2
  - [x] Catéter nasal de alto fluxo - era Cânula nalsal de alto fluxo
  - [x] **Máscara de Venturi - foi adicionado**
  - [x] Máscara com reservatório - era  Máscara de reservatório
  - [x] **Ventilação mecânica não Invasiva (VNI) - foi adicionado**
  - [x] Ventilação mecânica invasiva - era Ventilação invasiva
  - [x] Intubação Orotraqueal - era Tubo
  - [x] Traqueostomia (fica igual)
  - [x] **Oxigenação por membrana extracorpórea (ECMO) - foi adicionado**
  - [x] Pronação (fica igual)
  - [x] Inclusão em desmame da ventilação mecânica - era Inclusão no desmame da VM

- [x]  Atentar para os campos de **Máscara de Venturi** e **Oxigenação por membrana extracorpórea (ECMO)** que tiveram a inclusão de campos novos.

- [x]  O campo parâmetro passou a se chamar Fluxo O2

2020-10-07 20:42 UTC, MatheusVarela19 approved these changes

2020-10-08 17:07 UTC, chicaothiago reviewed
Fiz alguns comentários, no aguardo do feedback.

2020-10-08 17:07 UTC, chicaothiago commented on src/components/SnackBar/index.js
> +  );
Não é necessária alteração, mas fica o alerta de que não precisa de React.Fragment "<></>" quando se tem só uma, e o código fica mais limpo.

2020-10-08 17:07 UTC, chicaothiago commented on src/views/RespiratorySupport/components/FieldComposerForm/FieldComposerForm.js
> +};
Recomendo criar um novo componente, pode ser aqui neste arquivo mesmo, com o nome FieldGrid por exemplo para evitar toda essa replicação de código, apesar de algumas diferenças, da para fazer isso.

2020-10-08 17:07 UTC, chicaothiago commented on src/views/RespiratorySupport/components/FieldComposerItem/FieldComposerItem.js
> +import React from 'react';
O mesmo do comentário do arquivo anterior, agora que o código é similar em dois arquivos, pode ser possível de ser criar separado e reutilizar.

2020-10-08 19:15 UTC, FelipeSVidal commented on src/views/RespiratorySupport/components/RespiratorySuportItem/RespiratorySuportItem.js
> +            item
O material reclamou disto não? Porque não deveria ser possível container e item estarem juntos no mesmo Grid.

2020-10-08 19:15 UTC, FelipeSVidal commented on src/views/RespiratorySupport/components/RespiratorySuportItemList/RespiratorySuportItemList.js
> +      item
idem anterior

2020-10-08 19:19 UTC, ericsonmoreira commented on src/views/RespiratorySupport/components/RespiratorySuportItem/RespiratorySuportItem.js
> +            item
Totalmente normal isso. Na verdade essas duas propriedades não são conflitantes. Um _Grid_ pode ser _item_ e _container_ ao mesmo tempo. [Ola aqui a referência.](https://material-ui.com/pt/components/grid/#nested-grid)

2020-10-08 19:20 UTC, ericsonmoreira commented on src/views/RespiratorySupport/components/RespiratorySuportItemList/RespiratorySuportItemList.js
> +      item
Respondido no anterior.

2020-10-08 19:20 UTC, FelipeSVidal requested changes
Pensando numa futura componentização dos formulário, a ideia de criar um componente no lugar do FieldComposer seja uma opção melhor.

2020-10-08 19:22 UTC, ericsonmoreira commented on src/components/SnackBar/index.js
> +  );
Coloquei isso só pq quando eu salvava o arquivo, o linter bugava. Ai deixei dentro de um React.Fragment para parar de dar erro.

2020-10-08 19:25 UTC, ericsonmoreira commented on src/views/RespiratorySupport/components/FieldComposerForm/FieldComposerForm.js
> +};
Eu tinha começado a fazer desse jeito mas estava complicando mais do que ajudando. Mas vou dar uma olhada.

2020-10-08 20:41 UTC, ericsonmoreira commented on src/views/RespiratorySupport/components/FieldComposerItem/FieldComposerItem.js
> +import React from 'react';
Acho que criar separa do seria melhor.

2020-10-09 15:18 UTC, FelipeSVidal approved these changes

2020-10-09 15:51 UTC, merged