Fix/breadcrumbs general info
EscolaDeSaudePublica/registrocovid-front pull request #116
Opened 2020-10-07 22:12 UTC by MatheusVarela19

2020-10-08 18:35 UTC, FelipeSVidal approved these changes

2020-10-09 17:30 UTC, chicaothiago requested changes

2020-10-09 17:30 UTC, chicaothiago commented on src/views/GeneralInfo/GeneralInfo.js
> +        {console.log(patient)}
remover log

2020-10-09 17:30 UTC, chicaothiago commented on src/views/GeneralInfo/GeneralInfo.js
> +        )}
O que muda aqui é só o link, tu pode fazer este condicional fora do return, salvando em uma variável
`const links = patien.id ? [] : []`
E aqui só fazer o retorno simples do componente.

2020-10-09 17:36 UTC, MatheusVarela19 reviewed
Done!

2020-10-09 17:36 UTC, MatheusVarela19 commented on src/views/GeneralInfo/GeneralInfo.js
> +        )}
Saquei.

2020-10-09 17:36 UTC, MatheusVarela19 commented on src/views/GeneralInfo/GeneralInfo.js
> +        {console.log(patient)}
Ok, removendo!

2020-10-09 18:10 UTC, chicaothiago requested changes

2020-10-09 18:10 UTC, chicaothiago commented on src/views/GeneralInfo/GeneralInfo.js
> +    />
o ternário deveria ser do array, não do componente. Isso replica código de forma desnecessária

`return <CUstomBreadcrumbs links={links}`

2020-10-09 18:12 UTC, ericsonmoreira requested changes

2020-10-09 18:12 UTC, ericsonmoreira commented on src/views/GeneralInfo/GeneralInfo.js
> +
Acho que já comentaram, mas faz o `links` ser condicional. Fica mais _elegante_. :nail_care:

2020-10-09 18:16 UTC, ericsonmoreira reviewed
GMT :+1:

2020-10-09 18:17 UTC, chicaothiago approved these changes

2020-10-09 18:17 UTC, ericsonmoreira approved these changes

2020-10-09 18:18 UTC, merged

2020-10-09 18:22 UTC, MatheusVarela19 commented on src/views/GeneralInfo/GeneralInfo.js
> +
beleuza