Bugfix/bug exames complementares
EscolaDeSaudePublica/registrocovid-front pull request #138
Opened 2020-10-19 19:47 UTC by ericsonmoreira

## Dentro do Escopo

- [x] Verificar porque estava dando erro "ALGO DE ERRADO ACONTECEU" e porque não estava salvando.
- [x] Verificar porque a usuária conseguiu salvar 3x
- [ ] Verificar com a Camila a exclusão dos ítens repetidos.

## O que foi feito

1. Mudei o Layout para o field de Resultado ser maior (3 linhas) tanto no formulário como na componente de apresentação dos dados.
2. Adicionei uma validação para o field Resultado: 

|  Validação  |  Mensagem de Erro  |
|  -------------  |  --------------------------  |
|  **Máximo de 100 chars**  |   _Máximo de 100 caracteres_   |

2020-10-20 12:47 UTC, camilaccolares commented
Entradas excedentes excluídas (paciente 126).

2020-10-21 16:15 UTC, chicaothiago requested changes

2020-10-21 16:15 UTC, chicaothiago commented on src/views/ComplementaryTests/schema.js
> +        .max(100, 'Máximo de 100 caracteres'),
A task não altera o máximo para 1000?

2020-10-21 18:03 UTC, MatheusVarela19 requested changes
Ericson, na descrição do card, creio que a mensagem exibida e a validação não batem: uma diz **máx 100** e a outra diz **máx 1000**.

2020-10-21 18:24 UTC, ericsonmoreira commented on src/views/ComplementaryTests/schema.js
> +        .max(100, 'Máximo de 100 caracteres'),
Eu tinha colocado **max 100 chars** pq era o que tinha no momento em que eu fiz esse código. Inclusive, vamos mudar tudo, pois, de acordo com o que foi combinado na dayle de hj, o que vai acontecer é que uma nova **migration** será feita para que esses campos que iriam ficar com max de 1000 chars sejam agora do tipo **text**.

2020-10-21 19:19 UTC, ericsonmoreira commented
Pessoas, como foi acertado hj na dayle, o que vai acontecer é que esses campos que estavam causando em erro quando o usuário preenchia mais de 100 caracteres vão agora ser do tipo TEXT. Então removi todas as validações de max de 100 ou 1000 char que eu havia colocado.

2020-10-22 18:26 UTC, FelipeSVidal approved these changes

2020-10-23 17:06 UTC, chicaothiago approved these changes

2020-10-26 19:02 UTC, merged