Feature/more validation info gerais
EscolaDeSaudePublica/registrocovid-front pull request #150
Opened 2020-10-21 21:29 UTC by ericsonmoreira

## Validações

### Campo **Data de Internação**: 

| Validação  |  Mensagem de Erro  |
| ------------------- | ------------------- |
|  **>= 01/01/2020** |  Deve ser posterior ou igual à 01/01/2020 |
|  **<= data(hoje)** | Deve ser anterior ou igual a data de hoje (formato dd/mm/aaaa)  |

### Campo **Data do atendimento na unidade que referenciou o paciente**:

| Validação  |  Mensagem de Erro  |
| ------------------- | ------------------- |
|  **>= 01/01/2020** |  Deve ser posterior ou igual à 01/01/2020 |
|  **<= data(hoje)** | Deve ser anterior ou igual a data de hoje (formato dd/mm/aaaa)  |

2020-10-22 18:28 UTC, FelipeSVidal approved these changes

2020-10-23 17:25 UTC, chicaothiago requested changes

2020-10-23 17:25 UTC, chicaothiago commented on src/views/Comorbidities/Comorbidities.js
> +  }, [addToast, patient.id]);
Todas as consultas devem ser refeitas baseando-se no id do paciente? Se não, acredito que separar em outro use effects para ser chamado somente uma vez.

2020-10-23 17:25 UTC, chicaothiago commented on src/views/Comorbidities/Comorbidities.js
> +  }, [apiValues, allDoencas, tiposDoenca]);
Em outro PR há a mesma situação, e eu acredito que um componente que se baseiei  no tipoDoenca para gerar esses componente de doenças seja melhor utilizado pois evitará logica replicada em dois arquivos diferentes.
`ListaTiposDoencas`

2020-10-23 17:25 UTC, chicaothiago commented on src/views/Comorbidities/Comorbidities.js
> +      submitData.puerperio_semanas = values.puerperio_semanas;
Mesmo lance de linter e clean code, se quebrar a linha no if é recomendável usar chaves { }, no contrário manter na mesma linha.

2020-10-23 17:25 UTC, chicaothiago commented on src/views/GeneralInfo/schema.js
> +    .min('01/01/2020', 'Deve ser posterior ou igual à 01/01/2020')
Interessante ele validar a versão ptBR da data :D

2020-10-23 18:28 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +  }, [addToast, patient.id]);
Depois que esse componente é carregado, o paciente não muda. O _addToast_ e _patient.id_ estão nesse _array_ de dependências por que gera warnings no React. Tem tbm a questão que esse prática é recomendada pela comunidade do React.

2020-10-23 18:31 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +  }, [apiValues, allDoencas, tiposDoenca]);
Pois é @chicaothiago. Eu até comentei posteriormente que isso já foi de outra _feature_. Esse código ai foi alterado na para parar o _warning_ da falta de elementos no _array_ de dependências.

2020-10-23 18:32 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +      submitData.puerperio_semanas = values.puerperio_semanas;
Ok :+1:

2020-10-26 17:48 UTC, chicaothiago requested changes

2020-10-26 17:48 UTC, chicaothiago commented on src/views/Comorbidities/Comorbidities.js
> +  }, [addToast, patient.id]);
Como o primeiro parãmetro do useEffects é uma função, eu criava uma função e deixava ela eternamente
```javascript
const handleUseEffects = () => {}
useEffects(handlUseEffects, [])
```

Desta forma ele não dava erro de dependência e só executa uma única vez.
Essa função handleUseEffects conterá todas a lógica de dentro do useEffect

Meu ponto nesse caso é só que quando leio o código eu imagino que sempre vai alterar, agora eu sei que não, mas quando revisitar o código vou me questionar novamente se esse negócio atualiza sempre. Aí, como executa só uma vez, a solução que mandei acima funciona.

2020-10-27 18:18 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +  }, [addToast, patient.id]);
@chicaothiago vamos fazer o seguinte: vou desfazer a inclusão desses atributos no array de dependência desse _useEffect_. Como essa parte do código não faz parte do escopo do card dessa issue, melhor deixar como estava para poder rever isso depois. Ok? (Detalhe: está acontecendo erro quando não existem **Comorbidades** cadastradas de um paciente)

2020-10-28 19:50 UTC, MatheusVarela19 approved these changes

2020-10-29 16:22 UTC, chicaothiago approved these changes

2020-10-30 20:38 UTC, merged