Feature/adjust validation exa lab expecifico
EscolaDeSaudePublica/registrocovid-front pull request #179
Opened 2020-12-08 18:01 UTC by ericsonmoreira

## Escopo
Ajustar as validações de obrigatoriedade dos campos abaixo:
- **Exame RT-PCR**
  - Sítio da amostra RT-PCR
  - Data de coleta RT-PCR
- **Exame teste Rápido**
  - Data de coleta de teste rápido

No Exame RT-PCR não teremos nenhum campo obrigatório,  a **data do resultado** e **resultado** são os identificadores deste exame > Se não tiver nenhuma informação preenchida, o exame não deve ser enviado para o backend. E ao tentar salvar o formulário, sem estas informações o Front, deve apresentar a seguinte mensagem de erro (Toast): **Não foi possível salvar pois campos obrigatórios não foram informados.**

### Critérios de Aceite
- [x] 1.  **Data e Sítio da amostra RT-PCR - não devem ser campos obrigatórios**
   Dado que na página de Exames Laboratoriais Específicos da COVID-19, RT-PCR
   Quando inclua informações de Resultado e Data do Resultado
   Então ao clicar em salvar Não conste como obrigatório os demais campos de Data da Coleta e Sítio da Amostra

 - [x] 2.  **Data de coleta de Teste Rápido - não deve ser campo obrigatório**
   Dado que na página de Exames Laboratoriais Específicos da COVID-19, Teste Rápido
   Quando inclua informações de Resultado 
   Então ao clicar em salvar Não conste como obrigatório o campo de Data da Coleta de Teste Rápido

- [x] 3.  **Data de resultado e Resultado da amostra RT-PCR -  devem ser campos identificadores**
   Dado que na página de Exames Laboratoriais Específicos da COVID-19, RT-PCR
   Quando Não inclua informações de Resultado e Data do Resultado
   Então ao clicar em salvar, apareça a mensagem de erro: Não foi possível salvar pois campos obrigatórios não foram informados

2020-12-09 14:22 UTC, chicaothiago requested changes

2020-12-09 14:22 UTC, chicaothiago commented on src/views/SpecificsTests/schema.js
> -      ),
Apesar das condições estarem sendo validadas na hora do submit, ao remover estes campos aqui o fator de obrigatoriedade no campo em si também é removido, como o *.

Além da mensagem de erro não informar o que realmente é obrigatório ser inserido.

As condições da atividade não é remover a obrigatoriedade sempre de todos os componentes. 
É para remover obrigatoriedade SE algo acontecer. 
Verificar novamente os casos.

2020-12-09 22:06 UTC, ericsonmoreira commented on src/views/SpecificsTests/schema.js
> -      ),
Consegui uma maneira de mostrar uma mensagem de erro pra cada form que é apresentado caso a validação necessária seja desobedecida. Agora precisamos definir a mensagem que aparecerá.

2020-12-11 13:16 UTC, chicaothiago reviewed
Só uma dúvida para ter certeza que está executando da forma correta.

2020-12-11 13:16 UTC, chicaothiago commented on src/models/specificsTests/SpecificsTestsService.js
> +    api.post(`/pacientes/${patientId}/exames-laboratoriais`, test),
Uma dúvida, ele chama aqui a request?
Eu só crio um array quando vou fazer um Promise.all com a lista de promessas. 
Eu não sei se o JS já chama aqui no loop do map, se sim, que louco hahaha.
Acredito que a vírgula no final seja do lint.

2020-12-15 17:27 UTC, ericsonmoreira commented on src/models/specificsTests/SpecificsTestsService.js
> +    api.post(`/pacientes/${patientId}/exames-laboratoriais`, test),
Até onde sei, as requests só serão chamadas no momento do **Promise.all()**.

2020-12-15 17:33 UTC, chicaothiago approved these changes

2021-01-05 17:53 UTC, merged