Feature/join exames fisicos e suporte respiratorio
EscolaDeSaudePublica/registrocovid-front pull request #193
Opened 2021-01-08 19:06 UTC by ericsonmoreira

### Contexto

   A coleta de dados sobre a utilização de suportes respiratórios é realizada diariamente e sofre alterações constantes, podendo ser estas no decorrer do dia ou da semana. Portanto, a inserção dessas informações de forma diária é mais valiosa para a realização das análises. Atualmente, a página de Suporte Respiratório colhe datas de inicio e término, sem levar em consideração a informação diária sobre o suporte utilizado pelos pacientes. 

### Dentro do escopo

Unificar a página de **Exames físicos (admisão e evolução diária)** com a página de **Suporte Respiratório**. Será necessário trazer os formulários de suporte respiratório para dentro da página de exame físico.  [Conforme protótipo](https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=595%3A162)
- Nesse card iremos retirar as datas que constam nos formulários de suporte respiratório, uma vez que a data da evolução será a data do exame físico
- O nome da categoria **"Exame Físico (admisão e evolução diária)"** deverá ser alterado para **"Evolução diária"**. O nome dessa categoria deve ser alterado em todos os locais em que ela estiver referenciada. (página de categorias e página de Evolução diária intermediária)
- A categoria **Suporte Respiratório** deixará de existir como categoria, pois ela será unificada com a página de **Exames Físicos.**

2021-01-11 20:23 UTC, chicaothiago requested changes

2021-01-11 20:23 UTC, oxechicao commented on src/views/DailyEvolution/DailyEvolution.jsx
> +      console.log(response);
remover console log

2021-01-11 20:23 UTC, oxechicao commented on src/views/DailyEvolution/DailyEvolution.jsx
> +      console.log(error);
remover console.log

2021-01-11 20:23 UTC, oxechicao commented on src/views/DailyEvolution/DailyEvolution.jsx
> +      console.log(response.suportesRespiratorios);
esqueceu do TODO :D

2021-01-11 20:23 UTC, chicaothiago commented on src/views/DailyEvolution/components/RespiratorySuportItem/RespiratorySuportItem.js
> +        {[1, 2, 4].some(id => suporteRespiratorio.tipo_suporte_id === id) && (
Esse bloco de form não é o mesmo do `RespiratorySuportForm`.3

2021-01-11 21:25 UTC, ericsonmoreira commented on src/views/DailyEvolution/DailyEvolution.jsx
> +      console.log(response.suportesRespiratorios);
Fiquei tão emocionado por ter acabado a atividade que esqueci dos meus **TODOs** 💩 kkkkk

2021-01-11 21:42 UTC, ericsonmoreira commented on src/views/DailyEvolution/components/RespiratorySuportItem/RespiratorySuportItem.js
> +        {[1, 2, 4].some(id => suporteRespiratorio.tipo_suporte_id === id) && (
Não @chicaothiago. Em um eu uso o **FieldComposerItem** e em outro eu uso o **FieldComposerForm**. A diferença básica é que em um deles eu uso o componente que usa o Formik e no outro é só para exibir os dados.

2021-01-12 00:35 UTC, chicaothiago commented on src/views/DailyEvolution/components/RespiratorySuportItem/RespiratorySuportItem.js
> +        {[1, 2, 4].some(id => suporteRespiratorio.tipo_suporte_id === id) && (
Ah, beleza, nossa, que pegadinha hahahahahaha. Dará um ótimo professor :P

2021-01-12 00:36 UTC, chicaothiago approved these changes

2021-01-12 17:23 UTC, merged