Feature/historico listagem exame fisico
EscolaDeSaudePublica/registrocovid-front pull request #41
Opened 2020-08-26 13:32 UTC by Edely

Insere Listagem de Exames Físicos.

2020-08-26 13:38 UTC, vicmagpac submitted a review, later dismissed

2020-08-26 14:01 UTC, felip-carvalho requested changes
Edely, dá uma olhadinha nos comentários que fiz em seu arquivo `PhysycalExamList.js` 😄

2020-08-26 14:01 UTC, felip-carvalho commented on src/views/PhysicalExamsList/PhysicalExamsList.js
> +  const transformDate = rawDate => {
Legal a forma que você fez para formatar as datas Edely! Mas só uma dúvida, a função `formateDate.js` que se encontra na pasta **src/helpers** não serviu para realizar esse tratamento de datas?

2020-08-26 14:01 UTC, felip-carvalho commented on src/views/PhysicalExamsList/PhysicalExamsList.js
> +        <Breadcrumbs
Aqui temos um componente chamado `CustonBreadcrumbs.js` dentro da pasta **src/components** que facilita na hora de criar esses Breadcrumbs e diminui a verbosidade do seu código. Dá uma olhadinha em outras páginas que já utilizam esse componente, qualquer dúvida de como implementar me avisa.

2020-08-28 17:21 UTC, felip-carvalho approved these changes

2020-08-28 18:25 UTC, vicmagpac approved these changes

2020-08-28 18:25 UTC, merged