Feature/bug comorbidades
EscolaDeSaudePublica/registrocovid-front pull request #88
Opened 2020-09-21 18:58 UTC by ericsonmoreira

## Ajustes

- [x] **Campo Outras Condições:**
- Fazer verificação antes de adicionar - se o campo estiver vazio, não deve permitir adicionar (coletador clica e nada deve acontecer).

- [x] **Medicações de uso Continuo:**
- Fazer verificação antes de adicionar - se o campo estiver vazio, não deve permitir adicionar (coletador clica e nada deve acontecer).

- [x] **"Acrescente outras doenças que o paciente apresenta":**
  - [x] Campo de adicionar só pode estar habilitado quando o coletador selecionar uma doença.
  - [x] Após a doença ser salva, o botão de excluir o card deve desaparecer.

- [x] Verificar se os formulários de doenças estão buscando todos os campos. Deve ficar igual ao [figma](https://www.figma.com/file/1NBrCq4yx1A85TzvlHW1Gs/Registro-COVID?node-id=355%3A491)

2020-09-21 20:53 UTC, MatheusVarela19 approved these changes

2020-09-21 21:00 UTC, FelipeSVidal commented on src/views/Comorbidities/Comorbidities.js
> +    //   });
Melhor apagar essas linhas!

2020-09-21 21:05 UTC, FelipeSVidal requested changes
Só para usar o padrão do layout, como tá na documentação do material-ui!

2020-09-21 21:05 UTC, FelipeSVidal commented on src/views/Comorbidities/OutrasDoencasItem.js
> +      >
Usa <Grid container ... >, para padronizar o layout do grid!

2020-09-21 22:27 UTC, dayanyespindola approved these changes
+1 no comentário no Vidal e no mais approve ;)

2020-09-21 22:27 UTC, dayanyespindola commented on src/views/Comorbidities/Comorbidities.js
> +    // eslint-disable-next-line
Faz sentido desabilitar ou o eslint tá reclamando de uma dependência que realmente deveria estar aqui?

2020-09-22 03:15 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +    //   });
Nossa... Deixei passar isso. Concertarei.

2020-09-22 03:20 UTC, ericsonmoreira commented on src/views/Comorbidities/Comorbidities.js
> +    // eslint-disable-next-line
Eu tentei corrigir os _warnings_ que apareceram. Mas o **app** começou a dar problemas. Dai coloquei esse comentário para parar de alertar.

2020-09-22 03:25 UTC, ericsonmoreira commented on src/views/Comorbidities/OutrasDoencasItem.js
> +      >
Peguei esse código para concertar uns bugs... inicialmente, não fui eu quem fez ele. Dai eu preferi manter essa parte do código. Mas vou dar uma olhada nisso.

2020-09-22 16:02 UTC, FelipeSVidal approved these changes

2020-09-22 17:05 UTC, merged