Hotfix/personal history adjustment #85
EscolaDeSaudePublica/registrocovid-front pull request #89
Opened 2020-09-21 20:47 UTC by FelipeSVidal

2020-09-22 16:31 UTC, ericsonmoreira commented on src/views/PersonalHistory/PersonalHistory.js
>            key={String(Math.random())}
Número **randon** para o _key_... grandes chances para dar errado. Seria melhor colocar: 
```javascript
 {items.map((item, index) => (
        <div
          key={index}
  // resto do código.
```

2020-09-22 16:32 UTC, ericsonmoreira requested changes
Tem um **randon** sendo passado pra um _key_.

2020-09-22 17:18 UTC, FelipeSVidal commented on src/views/PersonalHistory/PersonalHistory.js
>            key={String(Math.random())}
Alteração feita! 
Como não fomos nós que fizemos, pode ser que tenha em outros arquivos esse mesmo problema, vou dar uma olhada se em mais algum arquivo tem algo parecido!

2020-09-23 17:52 UTC, MatheusVarela19 approved these changes

2020-09-23 18:05 UTC, ericsonmoreira approved these changes

2020-09-23 18:05 UTC, merged