Feature/redo layout
EscolaDeSaudePublica/registrocovid-front pull request #94
Opened 2020-09-22 18:50 UTC by MatheusVarela19

2020-09-22 18:57 UTC, ericsonmoreira commented
Tem conflitos para resolver.

2020-09-23 18:19 UTC, FelipeSVidal requested changes
Por que foi retirado o Grid do SignIn? Ideal é usar o Grid pela responsividade!

2020-09-23 18:19 UTC, FelipeSVidal commented on public/index.html
> +  <link rel="shortcut icon" style="text-shadow: 0 0 10px #000;" href="%PUBLIC_URL%/favicon.ico" />
Estilo não aplica, remover para evitar possíveis erros.

2020-09-23 19:00 UTC, ericsonmoreira approved these changes

2020-09-23 19:19 UTC, FelipeSVidal approved these changes

2020-09-23 20:35 UTC, merged