Hotfix/ajustes exames fisicos
EscolaDeSaudePublica/registrocovid-front pull request #95
Opened 2020-09-22 20:33 UTC by MatheusVarela19

2020-09-23 11:37 UTC, ericsonmoreira commented
Precisa resolver os conflitos.

2020-09-23 18:14 UTC, ericsonmoreira commented on src/views/PhysicalExamsList/PhysicalExamsList.js
> +                <Placeholder />
O que é esse Placeholder?

2020-09-23 18:20 UTC, FelipeSVidal commented on src/views/PhysicalExamsList/PhysicalExamsList.js
> +                <Placeholder />
É a imagem de quando não tem exames físicos!

2020-09-23 19:03 UTC, ericsonmoreira commented on src/views/PhysicalExamsList/PhysicalExamsList.js
> +                <Placeholder />
Olha depois a **develop** que tem um _component_ pra isso. Está em _src/components/_.

2020-09-24 10:56 UTC, mauricioholanda1 approved these changes

2020-09-24 15:37 UTC, ericsonmoreira requested changes
Pessoal, eu olhei o _component_ que Placeholder que está sendo usado aqui e não achei legal. Deem uma olhada no _component_ **NotToShowImg**. 

```javascript
import React from 'react';
import { Typography } from '@material-ui/core';
import PropTypes from 'prop-types';
import { makeStyles } from '@material-ui/styles';

const useStyles = makeStyles(theme => ({
  root: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: {
    color: 'rgba(0, 0, 0, 0.54)',
  },
  image: {
    marginBottom: theme.spacing(4),
    maxWidth: '100%',
    maxHeight: '100%',
  },
}));

/**
 * Componete para mostar uma IMG quando não tem nada para mostar.
 */
const NotToShowImg = props => {
  const { label } = props;

  const classes = useStyles();

  return (
    <div className={classes.root}>
      <img
        alt="nenhum paciente cadastrado"
        className={classes.image}
        src="/images/not_to_show.svg"
      />
      <Typography
        className={classes.label}
        variant="h3"
      >
        {label}
      </Typography>
    </div>
  );
};

NotToShowImg.propTypes = {
  label: PropTypes.string.isRequired,
};

export default NotToShowImg;
```
O que acham de usar ele? Ele já está na _develop_.

2020-09-24 20:10 UTC, MatheusVarela19 commented on src/views/PhysicalExamsList/PhysicalExamsList.js
> +                <Placeholder />
Resolvido!

2020-09-24 20:30 UTC, ericsonmoreira approved these changes
GTM :+1:

2020-09-24 20:30 UTC, merged